# FLANKOPHILE version 0.0.4
# Alex Thorn


## 0 ##

database: "input/example_input_files/Resfinder_08_02_2022_dub_rem.fa"         # a multifasta file

## 1 ##

#input_format: "contigs"
input_format: "assemblies"                                # "assemblies" for assembly list.  "contigs" for contigs list.

input_list: "input/example_input_files/test_input_1000_assemblies_list.tsv"               # Path to input_list.
                                                          
                                                          

# For "assemblies": input_list is a tsv file with assembly/sample/bin name in collumn 1 and
#  full path to fasta in collumn 2.

# For "contigs": input_list is a tsv file with assembly/sample/bin name in collumn 1 and
# contig name in collumn 2. Full path to assembly fasta in collumn 3. This option is used
# when you are only interested in certain contigs from each multi fasta but it
# is to much work to make new induvidual fastas for these contigs.

 
## 2 ##

flank_length_upstreams: "3000"

flank_length_downstreams: "3000"

min_coverage_abricate: "95"   # percentage

min_identity_abricate: "95"   # percentage


## 4 ##

cluster_identity_cd_hit: "0.95"       # -c 

cluster_wordsize_cd_hit: "9"        # -n 

cluster_length_dif_cd_hit: "0.9"     # -s 

#See https://github.com/weizhongli/cdhit/wiki/3.-User's-Guide#CDHITEST


## 5 ##

Kmersize_kma: "16"                       # Kmersize used by kma index. Try with "16" if in doubt.  

distance_measure: "1" # Choose measurement for making distance matrix 



# Distance calculation methods:
#
#        1      k-mer hamming distance
#       64      Jaccard distance
#      256      Cosine distance
#     4096      Chi-square distance


