# FLANKOPHILE version 0.0.2
# Alex Thorn


## 0 ##

database: "input/Resfinder_08_02_2022_dub_rem.fa"         # a multifasta file

## 1 ##

#input_format: "contigs"
input_format: "assemblies"                                # "assemblies" for assembly list.  "contigs" for contigs list.

#input_list: "input/test_input_contig_list.tsv"
input_list: "input/test_input_1000_assemblies_list.tsv"              # Path to input_list.
                                                          
                                                          

# For "assemblies": input_list is a tsv file with assembly/sample/bin name in collumn 1 and
#  full path to fasta in collumn 2.

# For "contigs": input_list is a tsv file with assembly/sample/bin name in collumn 1 and
# contig name in collumn 2. Full path to assembly fasta in collumn 3. This option is used
# when you are only interested in certain contigs from each multi fasta but it
# is to much work to make new induvidual fastas for these contigs.

 
## 2 ##

flank_length_upstreams: "1000"

flank_length_downstreams: "1000"

min_coverage_abricate: "95"   # percentage

min_identity_abricate: "95"   # percentage


## 4 ##

cluster_identity_cd_hit: "0.95"       # -c 

cluster_wordsize_cd_hit: "9"        # -n 

cluster_length_dif_cd_hit: "0.9"     # -s 

#See https://github.com/weizhongli/cdhit/wiki/3.-User's-Guide#CDHITEST


## 5 ##

distance_measure_flanks_masked_gene: "64" # Choose measurement for making distance matrix of the flanks of genes

distance_measure_just_gene: "64"          # Choose measurement for making distance matrix of genes


# Distance calculation methods:
#
#        1      k-mer hamming distance
#       64      Jaccard distance
#      256      Cosine distance
#     4096      Chi-square distance


