# FLANKOPHILE version 0.1.1
# Alex Vincent Thorn


## 1 ##

database: "input/example_input_files/ResFinder_08_02_2022.fa"         # a multifasta file

input_format: "assemblies"                     # "assemblies" for assembly list.  "contigs" for contigs list.
#input_format: "contigs"

input_list: "input/example_input_files/input_list_example_assembly_mode.tsv"               # Path to input_list.
                                                                                                               
 
## 2 ##

flank_length_upstreams: "2000"

flank_length_downstreams: "2000"

min_coverage_abricate: "95"   # percentage

min_identity_abricate: "95"   # percentage


## 4 ##

cluster_identity_cd_hit: "0.95"       # -c 

cluster_wordsize_cd_hit: "9"        # -n 

cluster_length_dif_cd_hit: "0.9"     # -s 

#See https://github.com/weizhongli/cdhit/wiki/3.-User's-Guide#CDHITEST


## 5 + 6 ##

Kmersize_kma: "16"                       # Kmersize used by kma index. Try with "16" if in doubt.  

distance_measure: "1" # Choose measurement for making distance matrix 



# Distance calculation methods:
#
#        1      k-mer hamming distance
#       64      Jaccard distance
#      256      Cosine distance
#     4096      Chi-square distance


